mod 'puppetlabs/stdlib', '5.2.0'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-translate'
mod 'puppetlabs/inifile', '3.1.0'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/ntp'
mod 'puppet-letsencrypt'
mod 'puppet-extlib', '3.1.0'
mod 'puppet-fail2ban',      :git => 'https://github.com/voxpupuli/puppet-fail2ban.git',            :branch => 'master'
mod 'puppet-ohmyzsh',       :git => 'https://github.com/rehanone/puppet-ohmyzsh',                  :branch => 'master'
mod 'base',                 :git => 'https://github.com/jlejeune/jlejeune.home-puppet-base.git',   :branch => 'master'
mod 'bash',                 :git => 'https://github.com/arnaudmorin/puppet-bash.git',              :branch => 'master'
mod 'ssh',                  :git => 'https://github.com/arnaudmorin/puppet-ssh.git',               :branch => 'master'
mod 'zsh',                  :git => 'https://github.com/jlejeune/puppet-zsh.git',                  :branch => 'feature_zsh'
