mod 'puppetlabs/stdlib'
mod 'puppetlabs/inifile'
mod 'puppetlabs/concat'
mod 'puppetlabs/apt'
mod 'puppetlabs/ntp',       '4.2.0'
mod 'base',                 :git => 'https://github.com/jlejeune/jlejeune.home-puppet-base.git',      :branch => 'master'
mod 'bash',                 :git => 'https://github.com/arnaudmorin/puppet-bash.git',           :branch => 'master'
mod 'zsh',                  :git => 'https://github.com/arnaudmorin/puppet-zsh.git',            :branch => 'master'
mod 'ssh',                  :git => 'https://github.com/jlejeune/puppet-ssh.git',            :branch => 'master'
